server:
  port: 8081
  servlet:
    context-path: /resource-server

####### resource server configuration properties
spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/demo1
          jwk-set-uri: http://localhost:8083/realms/demo1/protocol/openid-connect/certs
####### enable logging for spring security
logging:
  level:
    org:
      springframework:
        security: DEBUG